server:
	port: 8081
spring:
    datasource:
        url: jdbc:mysql://192.168.3.7:3306/business_college_dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&&useSSL=false
        username: root
        password: Root123!
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: update
    freemarker:
        allow-request-override: false
        cache: true
        check-template-location: true
        charset: UTF-8
        content-type: text/html
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: false
        suffix: .ftl
        template-loader-path: classpath:/templates/
        templateEncoding: UTF-8
    redis:
        host: 47.99.134.58
        port: 6379
        timeout: 0
file:
    path:
        show: /f/
        upload: /home/kevin/temp/