server:
    port: 8000
spring:
    datasource:
        url: jdbc:mysql://rm-m5epjm79t601ytlr7ho.mysql.rds.aliyuncs.com:3306/college_business_prod?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&&useSSL=false
        username: root
        password: Buildup34
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: update
    freemarker:
        allow-request-override: false
        cache: true
        check-template-location: true
        charset: UTF-8
        content-type: text/html
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: false
        suffix: .ftl
        template-loader-path: classpath:/templates/
        templateEncoding: UTF-8
    redis:
        host: r-m5e38585ed451b54.redis.rds.aliyuncs.com
        port: 6379
        password: Hejun1q2w3e
        database: 1
        timeout: 0
file:
    path:
        show: /f/
        upload: /data/college/temp/